Update setup.cfg
Setuptools v54.1.0 was released on March 5, 2021 and now requires setup.cfg being written in a different way


      setuptools.errors.InvalidConfigError: Invalid dash-separated key 'description-file' in 'metadata' (setup.cfg), please use the underscore name 'description_file' instead.